language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "8.0"
    - php: "nightly"
    - php: "master"
  allow_failures:
    - php: "nightly"
    - php: "master"

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer self-update --1; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer self-update --1; fi
  - composer update

script:
  - vendor/bin/phpunit
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ] && [${TRAVIS_PHP_VERSION:0:3} != "7.0"]]; then vendor/bin/psalm; fi
